# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'healthDevice' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'SwiftSocket'

  # Pods for healthDevice

end

target 'healthDevice WatchKit App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for healthDevice WatchKit App

end

target 'healthDevice WatchKit Extension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for healthDevice WatchKit Extension

end

